weights: best_NTU.pt
cfg: ''
data: ./data/mix_coco128.yaml
hyp: ./data/hyps/hyp.test1.yaml
epochs: 50
batch_size: 32
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: null
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: true
sync_bn: false
workers: 8
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: runs/train/exp17
